### ISSUE TITLE
Install release-it globally

### ISSUE THREAD

**Issue by webpro** [rwjblue/create-rwjblue-release-it-setup#105]
First of all, nice repo! :)

I saw a step in the release process saying "install release-it globally", and I traced it down to this repository. But I wonder whether this is the best option?

Generally it's good practice to add release-it to the `devDependencies`, so it will also automatically receive updates. Also, it's one manual step less in this process.

This could all be automated from the script in this repo, only the command to release would change from `release-it` to e.g. `npm run release` (or `yarn release`).

What do you think?

**Comment by rwjblue** [comment]
@webpro - Hey thanks for taking a look!

> This could all be automated from the script in this repo, only the command to release would change from release-it to e.g. npm run release (or yarn release).

This has non-trivial issues when using `yarn`. Specifically, even with `publishOptions` with `registry` set (which we do), calling `yarn release` does not work properly. 

> Generally it's good practice to add release-it to the devDependencies, so it will also automatically receive updates. Also, it's one manual step less in this process.

I actually _do_ add `release-it` in `devDependencies` ([see here](https://github.com/rwjblue/create-rwjblue-release-it-setup/blob/e37f5f944aa27f0eada5a01dc671bfa6bf2f6070/bin/rwjblue-release-it-setup.js#L105-L108)).

> I saw a step in the release process saying "install release-it globally", and I traced it down to this repository. But I wonder whether this is the best option?

My workflow is actually to use `volta install release-it`, which is not a normal global (it automatically uses the project local version if present, [see this blog post](https://blog.volta.sh/2019/06/18/global-installs-done-right/)). A comparable workflow (without `volta`) would be to use `npx release-it` since `npx` will intentionally defer to a project local `node_modules/.bin` if one is present, which is _exactly_ what my normal `volta` based setup does as well.

Either way, I totally agree that we don't really want `npm install -g release-it` / `yarn add --global release-it` being done. I'm happy to tweak the language in the generated `RELEASE.md` files to make the `npx` workflow clearer (and plausibly even the only thing we mention).

**Comment by rwjblue** [comment]
https://github.com/rwjblue/create-rwjblue-release-it-setup/pull/9 removed the `scripts` section, and has a bit more info (though sadly not exact error messages / stack traces):

> `yarn release` (even with `publishConfig` setting the registry) will think it is not authenticated properly.

**Comment by webpro** [comment]
Thanks for explaining everything!

So both `npx release-it` and `npm run release` strategies work without installing release-it globally. My issue with the description currently is that, by also supporting Yarn, the regular npm users may think they need to install this package globally. So making this more clear in the description would be great indeed. I think everyone is better off by users updating their dependencies (more frequently)  :-)

**Comment by webpro** [comment]
Thanks @rwjblue! I was actually looking at ./RELEASE.md when I opened this ticket, but obviously the template file is what's being used by the script.

**Comment by rwjblue** [comment]
Ah, good call, I’ll update this repos `RELEASE.md` as well.
