### ISSUE TITLE
unhandled rejection when running in npm repo

### ISSUE THREAD

**Issue by efx** [rwjblue/create-rwjblue-release-it-setup#6]
Thank you for this pro tip.
1. `git clone https://github.com/adopted-ember-addons/ember-page-title.git && cd ember-page-title`
2. run `npm init rwjblue-release-it-setup`

It works but I noticed the following printed to my terminal:
```bash
(node:7098) UnhandledPromiseRejectionWarning
(node:7098) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7098) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rwjblue** [comment]
Thanks for reporting! The last I looked into this, it was because the GH api is returning a redirect and the system I’m using to setup github labels doesn’t properly handle redirects. I reported that over in https://github.com/Financial-Times/github-label-sync/issues/27 but haven’t seen any movement (the repo seems to be fairly silent in the last few months).

At the least, we should add a catch handler to our main to avoid the node warning RE: unhandled rejections, and then log the error to the console.
